version: '3.5'
services:
  app:
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app/src
    networks:
      - local_dev_network
  mongodb:
    ports:
      - '27027:27017'
    volumes:
      - 'mongodb-volume:/data/db'
volumes:
  mongodb-volume:
    driver: local